# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/KimberlySalazarB/prueba/blob/main/Untitled17.ipynb
"""
print("Hola")
print("hola mundo")

from __future__ import print_function

import pandas as pd
pd.__version__

print("hola")

# Descripción del conjunto de datos
print("Descripción del conjunto de datos:")
print(data.head())

data.describe()





































